import type { ReleaseType } from './types'

export const EMOJI_MAP: Record<string, string> = {
  rocket: '🚀',
  tada: '🎉',
  sparkles: '✨',
  bug: '🐛',
  fire: '🔥',
  package: '📦',
  wrench: '🔧',
  hammer: '🔨',
  construction: '🚧',
  warning: '⚠️',
  x: '❌',
  check: '✅',
  white_check_mark: '✅',
  heavy_check_mark: '✔️',
  arrow_up: '⬆️',
  arrow_down: '⬇️',
  art: '🎨',
  zap: '⚡',
  memo: '📝',
  pencil: '✏️',
  book: '📖',
  bookmark: '🔖',
  globe_with_meridians: '🌐',
  link: '🔗',
  lock: '🔒',
  unlock: '🔓',
  key: '🔑',
  mag: '🔍',
  bulb: '💡',
  bell: '🔔',
  loudspeaker: '📢',
  mega: '📣',
  chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉',
  bar_chart: '📊',
  calendar: '📅',
  hourglass: '⌛',
  hourglass_flowing_sand: '⏳',
  watch: '⌚',
  alarm_clock: '⏰',
  stopwatch: '⏱️',
  timer_clock: '⏲️',
  star: '⭐',
  star2: '🌟',
  dizzy: '💫',
  boom: '💥',
  collision: '💥',
  muscle: '💪',
  clap: '👏',
  pray: '🙏',
  handshake: '🤝',
  thumbsup: '👍',
  thumbsdown: '👎',
  ok_hand: '👌',
  point_right: '👉',
  point_left: '👈',
  point_up: '☝️',
  point_down: '👇',
  raised_hand: '✋',
  wave: '👋',
  eyes: '👀',
  brain: '🧠',
  heart: '❤️',
  broken_heart: '💔',
  green_heart: '💚',
  blue_heart: '💙',
  yellow_heart: '💛',
  purple_heart: '💜',
  black_heart: '🖤',
  white_heart: '🤍',
  orange_heart: '🧡',
  man_and_woman_holding_hands: '👫',
  woman_and_man_holding_hands: '👫',
  couple: '👫',
  two_men_holding_hands: '👬',
  two_women_holding_hands: '👭',
  busts_in_silhouette: '👥',
  family: '👪',
  man: '👨',
  woman: '👩',
  boy: '👦',
  girl: '👧',
  ladybug: '🐞',
  iphone: '📱',
  computer: '💻',
  phone: '📞',
  email: '📧',
  inbox_tray: '📥',
  outbox_tray: '📤',
}

export const RELEASE_TYPE_COLORS: Record<ReleaseType, string> = {
  'New Feature': 'bg-lime-100 text-lime-800',
  Improvement: 'bg-blue-100 text-blue-800',
  'Bug Fix': 'bg-red-100 text-red-800',
  Deprecation: 'bg-orange-100 text-orange-800',
  Rollback: 'bg-yellow-100 text-yellow-800',
  Update: 'bg-gray-100 text-gray-800',
}

export const DEFAULT_RELEASE_TYPE_COLOR = 'bg-gray-100 text-gray-800'

export const RELEASES_PAGE_SIZE = 100
